"""
消费者故事原型 — 抚心版：分手戒断人群（理性不复合 × 情感未戒断）。
以 JTBD（Job / Step / Outcome / Force）为顶层，人口学与分手状态（DetachInfo）绑定。
覆盖问卷 Q14 的 8 分群 × 2 位 = 16 原型，尽量铺满 J1–J7。
"""
from __future__ import annotations

from typing import Dict, List, Optional

PERSONA_ARCHETYPES: List[Dict] = [
    # ============ 1. 夜间脆弱型 ============
    {
        "key": "night_vulnerable_young",
        "seed_name": "小鹿",
        "segment": "夜间脆弱型",
        "role": "本人",
        "subject": "本人",
        "stage": "应激期",
        "detach_stage": "应激期",
        "weeks_since_breakup": 3,
        "relationship_months": 18,
        "contact_urge": 8,
        "relapse_count": 0,
        "safety_flag": False,
        "dominant": ["A8", "A11", "B1"],
        "decision_style": "敏感",
        "blockers": ["睡前忍不住翻回忆", "没有人可以倾诉", "天亮了又怪自己矫情"],
        "drivers": ["共情陪伴", "夜里有人接住", "被理解不说教"],
        "jtbd": {
            "job_id": "J3",
            "job_owner": "本人",
            "entry_situation": "凌晨醒来想TA",
            "current_step_id": "h",
            "desired_outcome_ids": ["O1", "O3", "O7"],
            "forces": {
                "push": ["A8", "A11"],
                "pull": ["B1"],
                "anxiety": ["A5"],
                "habit_or_alternative": [],
            },
        },
        "mindset": {
            "core_motive": "一到晚上就整个人垮掉，白天还能撑，凌晨三点最难熬。",
            "fear": "怕这种夜里崩溃永无休止，怕自己真的不正常。",
            "decision_logic": "先得有人接住我，再用睡眠仪式撑过夜晚。",
            "price_sensitivity": 5,
            "brand_anchor": "朋友推荐的温柔陪伴向工具",
            "channel_preference": "深夜也能随时打开的App",
            "quote": "我不是矫情，是凌晨三点的想念真的会把人吞掉。",
        },
    },
    {
        "key": "night_vulnerable_severe",
        "seed_name": "阿澄",
        "segment": "夜间脆弱型",
        "role": "本人",
        "subject": "本人",
        "stage": "复发应对期",
        "detach_stage": "复发应对期",
        "weeks_since_breakup": 8,
        "relationship_months": 36,
        "contact_urge": 9,
        "relapse_count": 2,
        "safety_flag": False,
        "dominant": ["A5", "A8", "B2"],
        "decision_style": "矛盾",
        "blockers": ["夜里冲动最强", "喝多就想打电话", "自责反复循环"],
        "drivers": ["冲动延迟缓冲", "火灾发生前的提醒", "允许反复"],
        "jtbd": {
            "job_id": "J2",
            "job_owner": "本人",
            "entry_situation": "夜里冲动最强烈",
            "current_step_id": "e",
            "desired_outcome_ids": ["O4", "O1", "O2"],
            "forces": {
                "push": ["A5"],
                "pull": ["B2"],
                "anxiety": ["A4", "A5"],
                "habit_or_alternative": [],
            },
        },
        "mindset": {
            "core_motive": "冲动来得又急又猛，短信都打好了，就差手指按下去。",
            "fear": "怕某一晚真的发出那条消息，把好不容易撑住的放下全部打碎。",
            "decision_logic": "需要一道物理缓冲把冲动和行动隔开。",
            "price_sensitivity": 6,
            "brand_anchor": "「先等5分钟」式冷静工具",
            "channel_preference": "锁屏也能快速触达的提醒",
            "quote": "我知道不该联系，可手自己会动——得有人在那0.1秒拦住我。",
        },
    },
    # ============ 2. 反复联系型 ============
    {
        "key": "repeat_contact_impulsive",
        "seed_name": "大齐",
        "segment": "反复联系型",
        "role": "本人",
        "subject": "本人",
        "stage": "戒断行动期",
        "detach_stage": "戒断行动期",
        "weeks_since_breakup": 5,
        "relationship_months": 24,
        "contact_urge": 10,
        "relapse_count": 1,
        "safety_flag": False,
        "dominant": ["A5", "A4", "B2"],
        "decision_style": "冲动",
        "blockers": ["消息打好了又删", "节日特别想祝福", "喝完酒就想打电话"],
        "drivers": ["延迟5分钟", "写下来替代", "一个能拉住我的人"],
        "jtbd": {
            "job_id": "J2",
            "job_owner": "本人",
            "entry_situation": "编辑好消息又删掉",
            "current_step_id": "f",
            "desired_outcome_ids": ["O4", "O6", "O2"],
            "forces": {
                "push": ["A5"],
                "pull": ["B2"],
                "anxiety": ["A4"],
                "habit_or_alternative": [],
            },
        },
        "mindset": {
            "core_motive": "面子告诉我别联系，手却比脑子快——每次都是打完整段话才清醒。",
            "fear": "怕自己永远戒不掉这个毛病，让人看不起。",
            "decision_logic": "冲动要输给缓冲，先等五分钟再看值不值。",
            "price_sensitivity": 7,
            "brand_anchor": "「延迟」类成瘾戒断工具",
            "channel_preference": "无负担的轻量提醒",
            "quote": "我不是放不下TA，是放不下那个习惯性想点发送的自己。",
        },
    },
    {
        "key": "repeat_contact_occasion",
        "seed_name": "小满",
        "segment": "反复联系型",
        "role": "本人",
        "subject": "本人",
        "stage": "戒断行动期",
        "detach_stage": "戒断行动期",
        "weeks_since_breakup": 6,
        "relationship_months": 12,
        "contact_urge": 9,
        "relapse_count": 1,
        "safety_flag": False,
        "dominant": ["A5", "A4", "B2"],
        "decision_style": "摇摆",
        "blockers": ["生日新年特别想发祝福", "纪念日自动唤醒记忆", "被共同朋友问到近况"],
        "drivers": ["节日预案", "冲动延迟", "替代动作清单"],
        "jtbd": {
            "job_id": "J2",
            "job_owner": "本人",
            "entry_situation": "节日想发祝福",
            "current_step_id": "g",
            "desired_outcome_ids": ["O4", "O6", "O2"],
            "forces": {
                "push": ["A5"],
                "pull": ["B2"],
                "anxiety": ["A4"],
                "habit_or_alternative": [],
            },
        },
        "mindset": {
            "core_motive": "大年初一零点，手滑点进对话框——不是想复合，就是惯性。",
            "fear": "怕一次「正常问候」又把戒断归零。",
            "decision_logic": "节日要提前备好预案：那一刻做什么、不做什么。",
            "price_sensitivity": 5,
            "brand_anchor": "懂分手节点的提醒工具",
            "channel_preference": "能提前设置的高危日提醒",
            "quote": "祝福是真的，可我不能用祝福当联系的借口。",
        },
    },
    # ============ 3. 等待复合型 ============
    {
        "key": "waiting_reunion_secret",
        "seed_name": "也子",
        "segment": "等待复合型",
        "role": "本人",
        "subject": "本人",
        "stage": "应激期",
        "detach_stage": "应激期",
        "weeks_since_breakup": 2,
        "relationship_months": 30,
        "contact_urge": 9,
        "relapse_count": 0,
        "safety_flag": False,
        "dominant": ["A2", "A3", "B3"],
        "decision_style": "期待",
        "blockers": ["反复确认TA有没有新对象", "刷TA主页成了必修课", "潜意识还在等契机"],
        "drivers": ["数字隔离", "看清事实", "被点醒不复合理由"],
        "jtbd": {
            "job_id": "J1",
            "job_owner": "本人",
            "entry_situation": "反复确认TA有没有新对象",
            "current_step_id": "b",
            "desired_outcome_ids": ["O5", "O2", "O1"],
            "forces": {
                "push": ["A2", "A3"],
                "pull": ["B3"],
                "anxiety": ["A5"],
                "habit_or_alternative": ["A2"],
            },
        },
        "mindset": {
            "core_motive": "嘴上说不等了，但每天第一件事就是看TA有没有新动态。",
            "fear": "怕TA官宣新恋情，又怕彻底没了希望。",
            "decision_logic": "理智说该屏蔽，心里还想留一条线——最需要有人帮我把线剪断。",
            "price_sensitivity": 5,
            "brand_anchor": "讲分手事实的清醒工具",
            "channel_preference": "悄悄用、不被发现的App",
            "quote": "我知道该往前走了，可总想再等等看。",
        },
    },
    {
        "key": "waiting_reunion_stubborn",
        "seed_name": "果果",
        "segment": "等待复合型",
        "role": "本人",
        "subject": "本人",
        "stage": "戒断行动期",
        "detach_stage": "戒断行动期",
        "weeks_since_breakup": 4,
        "relationship_months": 42,
        "contact_urge": 8,
        "relapse_count": 0,
        "safety_flag": False,
        "dominant": ["A4", "A5", "B2"],
        "decision_style": "执念",
        "blockers": ["总想见最后一面", "不愿承认关系真的结束", "把未来幻想留在备忘录"],
        "drivers": ["缓冲机制", "事实回顾", "被允许不舍"],
        "jtbd": {
            "job_id": "J2",
            "job_owner": "本人",
            "entry_situation": "想见最后一面",
            "current_step_id": "c",
            "desired_outcome_ids": ["O4", "O2", "O6"],
            "forces": {
                "push": ["A5"],
                "pull": ["B2"],
                "anxiety": ["A4", "A6"],
                "habit_or_alternative": [],
            },
        },
        "mindset": {
            "core_motive": "「再见面一次就放下」——这个念头拖了我一个月。",
            "fear": "怕错过唯一可能，又怕见面后更放不下。",
            "decision_logic": "需要有人告诉我最后一面救不了我，还要把理由写清楚。",
            "price_sensitivity": 4,
            "brand_anchor": "能讲清「为什么不能复合」的工具",
            "channel_preference": "重视隐私的私密通道",
            "quote": "不是说放下就放下，我只是想体面地道别。",
        },
    },
    # ============ 4. 理性清醒型 ============
    {
        "key": "rational_clarity_self",
        "seed_name": "木子",
        "segment": "理性清醒型",
        "role": "本人",
        "subject": "本人",
        "stage": "稳定坚持期",
        "detach_stage": "稳定坚持期",
        "weeks_since_breakup": 10,
        "relationship_months": 20,
        "contact_urge": 5,
        "relapse_count": 0,
        "safety_flag": False,
        "dominant": ["B6", "B10", "A7"],
        "decision_style": "理性",
        "blockers": ["偶尔闪回自我怀疑", "生活还没完全立起来"],
        "drivers": ["生活秩序", "自我价值重建", "进展可视"],
        "jtbd": {
            "job_id": "J6",
            "job_owner": "本人",
            "entry_situation": "觉得自己还能把日子过起来",
            "current_step_id": "i",
            "desired_outcome_ids": ["O8", "O6", "O2"],
            "forces": {
                "push": ["A7"],
                "pull": ["B6", "B10"],
                "anxiety": [],
                "habit_or_alternative": [],
            },
        },
        "mindset": {
            "core_motive": "理智上早就想通了，现在就差把生活一点点拾起来。",
            "fear": "怕自己坚持得不够久，怕回到以前那种状态。",
            "decision_logic": "先立计划再行动，需要看得见的进展来确认自己在变好。",
            "price_sensitivity": 5,
            "brand_anchor": "成长型、有进度感的产品",
            "channel_preference": "习惯打卡与复盘类",
            "quote": "我不需要劝，我需要方法和一点一点看得见的进步。",
        },
    },
    {
        "key": "rational_clarity_rebuilder",
        "seed_name": "叙白",
        "segment": "理性清醒型",
        "role": "本人",
        "subject": "本人",
        "stage": "重建转化期",
        "detach_stage": "重建转化期",
        "weeks_since_breakup": 14,
        "relationship_months": 15,
        "contact_urge": 3,
        "relapse_count": 0,
        "safety_flag": False,
        "dominant": ["B10", "B6", "B11"],
        "decision_style": "自律",
        "blockers": ["偶尔被共同记忆绊一下", "担心复发的自己"],
        "drivers": ["日程秩序", "自我认同重建", "里程碑反馈"],
        "jtbd": {
            "job_id": "J6",
            "job_owner": "本人",
            "entry_situation": "把想TA的时间换成想做自己的时间",
            "current_step_id": "n",
            "desired_outcome_ids": ["O8", "O2", "O6"],
            "forces": {
                "push": [],
                "pull": ["B10", "B6", "B11"],
                "anxiety": [],
                "habit_or_alternative": [],
            },
        },
        "mindset": {
            "core_motive": "分手三个月，我想通了放下，现在想重新成为完整的自己。",
            "fear": "怕哪一天被一条消息打回原形。",
            "decision_logic": "用日程、里程碑和复盘把自己稳稳固定在新生活里。",
            "price_sensitivity": 5,
            "brand_anchor": "有体系、有成就感的成长工具",
            "channel_preference": "打卡+长远规划",
            "quote": "我不是在戒断，我是在重建。",
        },
    },
    # ============ 5. 自我价值受损型 ============
    {
        "key": "self_esteem_damaged_doubt",
        "seed_name": "双双",
        "segment": "自我价值受损型",
        "role": "本人",
        "subject": "本人",
        "stage": "应激期",
        "detach_stage": "应激期",
        "weeks_since_breakup": 4,
        "relationship_months": 28,
        "contact_urge": 7,
        "relapse_count": 0,
        "safety_flag": False,
        "dominant": ["A7", "B6", "B10"],
        "decision_style": "自卑",
        "blockers": ["觉得再也没人会爱我", "反复怀疑是自己不够好", "不敢照镜子面对自己"],
        "drivers": ["被肯定的小事", "重建兴趣", "一点点成就感"],
        "jtbd": {
            "job_id": "J6",
            "job_owner": "本人",
            "entry_situation": "觉得不会再有人爱我",
            "current_step_id": "b",
            "desired_outcome_ids": ["O8", "O3", "O1"],
            "forces": {
                "push": ["A7"],
                "pull": ["B6"],
                "anxiety": ["A7", "A11"],
                "habit_or_alternative": [],
            },
        },
        "mindset": {
            "core_motive": "TA离开让我觉得自己整个人被否定了，值得被爱吗？",
            "fear": "怕孤独一辈子，怕再谈恋爱也要被丢下。",
            "decision_logic": "需要先重建一点点「我很好」的证据，才有力气往前走。",
            "price_sensitivity": 5,
            "brand_anchor": "温暖的、肯定价值的陪伴型产品",
            "channel_preference": "不说教的倾诉与成长",
            "quote": "不是TA不值得，是我开始怀疑自己值不值得被爱。",
        },
    },
    {
        "key": "self_esteem_damaged_fear",
        "seed_name": "楠楠",
        "segment": "自我价值受损型",
        "role": "本人",
        "subject": "本人",
        "stage": "复发应对期",
        "detach_stage": "复发应对期",
        "weeks_since_breakup": 9,
        "relationship_months": 40,
        "contact_urge": 6,
        "relapse_count": 2,
        "safety_flag": False,
        "dominant": ["A7", "A11", "B4"],
        "decision_style": "脆弱",
        "blockers": ["破戒一次就觉得自己前功尽弃", "深夜反复否定自己"],
        "drivers": ["允许反复", "被理解的感觉", "不用完美也可以"],
        "jtbd": {
            "job_id": "J6",
            "job_owner": "本人",
            "entry_situation": "破戒后觉得前功尽弃",
            "current_step_id": "l",
            "desired_outcome_ids": ["O3", "O8", "O6"],
            "forces": {
                "push": ["A7"],
                "pull": ["B4", "B6"],
                "anxiety": ["A7"],
                "habit_or_alternative": [],
            },
        },
        "mindset": {
            "core_motive": "昨天没忍住看了TA的资料，一整天都在骂自己没出息。",
            "fear": "怕破戒意味着永远戒不掉。",
            "decision_logic": "最需要有人告诉我：反复不等于失败，今天重新开始就好。",
            "price_sensitivity": 6,
            "brand_anchor": "温暖的、允许不完美的方式",
            "channel_preference": "情绪接住型互动",
            "quote": "一次破戒不代表彻底失败，对吗？我需要有人这么说。",
        },
    },
    # ============ 6. 孤独依赖型 ============
    {
        "key": "lonely_dependent_abandoned",
        "seed_name": "纪子",
        "segment": "孤独依赖型",
        "role": "本人",
        "subject": "本人",
        "stage": "应激期",
        "detach_stage": "应激期",
        "weeks_since_breakup": 3,
        "relationship_months": 22,
        "contact_urge": 8,
        "relapse_count": 0,
        "safety_flag": False,
        "dominant": ["A1", "A11", "B9"],
        "decision_style": "依赖",
        "blockers": ["被抛弃感强", "怕朋友觉得我矫情", "一个人不知道干嘛"],
        "drivers": ["不评判的陪伴", "被看见", "低负担的联结"],
        "jtbd": {
            "job_id": "J5",
            "job_owner": "本人",
            "entry_situation": "被抛弃感强烈",
            "current_step_id": "g",
            "desired_outcome_ids": ["O7", "O6", "O1"],
            "forces": {
                "push": ["A1", "A11"],
                "pull": ["B9"],
                "anxiety": ["A6"],
                "habit_or_alternative": [],
            },
        },
        "mindset": {
            "core_motive": "TA走之后世界安静得可怕，我好像被整个世界丢下了。",
            "fear": "怕从此孤独终老，怕没人会再真正懂我。",
            "decision_logic": "我需要的是陪伴，不是大道理——得先有人陪着，才有力气独立。",
            "price_sensitivity": 6,
            "brand_anchor": "温暖社群/陪伴型平台",
            "channel_preference": "能随时找到同路人",
            "quote": "我不缺道理，缺的是有人在我哭的时候坐在旁边。",
        },
    },
    {
        "key": "lonely_dependent_empty",
        "seed_name": "夏夏",
        "segment": "孤独依赖型",
        "role": "本人",
        "subject": "本人",
        "stage": "戒断行动期",
        "detach_stage": "戒断行动期",
        "weeks_since_breakup": 6,
        "relationship_months": 16,
        "contact_urge": 7,
        "relapse_count": 0,
        "safety_flag": False,
        "dominant": ["A1", "B9", "B1"],
        "decision_style": "退缩",
        "blockers": ["周末无处可去", "社交圈突然空了", "不敢联系老朋友怕被问"],
        "drivers": ["低门槛社交", "同路人社群", "不追问的关心"],
        "jtbd": {
            "job_id": "J5",
            "job_owner": "本人",
            "entry_situation": "周末无处可去",
            "current_step_id": "k",
            "desired_outcome_ids": ["O7", "O6", "O2"],
            "forces": {
                "push": ["A1"],
                "pull": ["B9", "B1"],
                "anxiety": ["A11"],
                "habit_or_alternative": [],
            },
        },
        "mindset": {
            "core_motive": "以前周末都是两个人，现在一个人躺到天黑。",
            "fear": "怕被朋友问「你俩怎么了」，怕解释不清。",
            "decision_logic": "想找一群不用解释、天然懂我处境的人。",
            "price_sensitivity": 7,
            "brand_anchor": "重陪伴轻社交压力的平台",
            "channel_preference": "匿名的同路人小组",
            "quote": "我不想解释我的伤，我只想有人陪我慢慢走出来。",
        },
    },
    # ============ 7. 创伤恢复型 ============
    {
        "key": "trauma_recovery_ruminate",
        "seed_name": "卷卷",
        "segment": "创伤恢复型",
        "role": "本人",
        "subject": "本人",
        "stage": "戒断行动期",
        "detach_stage": "戒断行动期",
        "weeks_since_breakup": 5,
        "relationship_months": 34,
        "contact_urge": 6,
        "relapse_count": 1,
        "safety_flag": False,
        "dominant": ["A3", "A8", "B5"],
        "decision_style": "沉思",
        "blockers": ["聊天记录翻了上百遍", "听到特定歌就陷进去", "睡前自动回放细节"],
        "drivers": ["打断反刍的动作", "让念头流走的练习", "回到当下"],
        "jtbd": {
            "job_id": "J4",
            "job_owner": "本人",
            "entry_situation": "反复回看聊天记录",
            "current_step_id": "f",
            "desired_outcome_ids": ["O2", "O3", "O5"],
            "forces": {
                "push": ["A3", "A8"],
                "pull": ["B5"],
                "anxiety": ["A7"],
                "habit_or_alternative": ["A3"],
            },
        },
        "mindset": {
            "core_motive": "我不是放不下分手，是停不下来复盘——每翻一遍记录心就揪一下。",
            "fear": "怕越想越陷进去，怕这辈子走不出这个循环。",
            "decision_logic": "需要能打断反刍的替代动作和让念头过去的练习。",
            "price_sensitivity": 6,
            "brand_anchor": "正念/认知行为类工具",
            "channel_preference": "即时响应、打断型提醒",
            "quote": "道理我都懂，问题是脑子它不听话，一直回放。",
        },
    },
    {
        "key": "trauma_recovery_highrisk",
        "seed_name": "阿默",
        "segment": "创伤恢复型",
        "role": "本人",
        "subject": "本人",
        "stage": "复发应对期",
        "detach_stage": "复发应对期",
        "weeks_since_breakup": 7,
        "relationship_months": 32,
        "contact_urge": 5,
        "relapse_count": 3,
        "safety_flag": True,
        "dominant": ["A10", "B8", "B7"],
        "decision_style": "危机",
        "blockers": ["连续失眠与崩溃", "出现伤害自己的念头", "不敢跟家人说"],
        "drivers": ["有人发现我", "专业转介", "安全的紧急出口"],
        "jtbd": {
            "job_id": "J7",
            "job_owner": "本人",
            "entry_situation": "连续多日严重失眠与崩溃",
            "current_step_id": "j",
            "desired_outcome_ids": ["O9", "O1", "O7"],
            "forces": {
                "push": ["A10"],
                "pull": ["B7", "B8"],
                "anxiety": ["A10"],
                "habit_or_alternative": [],
            },
        },
        "mindset": {
            "core_motive": "撑了两周，夜里有过「就这样算了」的念头——不敢告诉任何人。",
            "fear": "怕说出来被当笑话，怕真的失控。",
            "decision_logic": "需要绝对安全的通道被专业的人接住，最好有人注意到我不对劲。",
            "price_sensitivity": 3,
            "brand_anchor": "专业危机干预与心理支持",
            "channel_preference": "紧急而有温度的热线/转介",
            "quote": "我怕的不是分手，是怕自己撑不到天亮。",
        },
    },
    # ============ 8. 高执行打卡型 ============
    {
        "key": "high_executor_checkin",
        "seed_name": "一舟",
        "segment": "高执行打卡型",
        "role": "本人",
        "subject": "本人",
        "stage": "稳定坚持期",
        "detach_stage": "稳定坚持期",
        "weeks_since_breakup": 11,
        "relationship_months": 26,
        "contact_urge": 4,
        "relapse_count": 0,
        "safety_flag": False,
        "dominant": ["B11", "B6", "B10"],
        "decision_style": "自律",
        "blockers": ["偶尔怀疑坚持有什么意义", "瓶颈期进度变慢"],
        "drivers": ["打卡天数", "里程碑", "看得见的进展"],
        "jtbd": {
            "job_id": "J6",
            "job_owner": "本人",
            "entry_situation": "靠打卡重建生活秩序",
            "current_step_id": "n",
            "desired_outcome_ids": ["O8", "O2", "O6"],
            "forces": {
                "push": [],
                "pull": ["B11", "B6", "B10"],
                "anxiety": [],
                "habit_or_alternative": [],
            },
        },
        "mindset": {
            "core_motive": "分手第 30 天开始打卡，第 47 天没断过——进度是我最大的动力。",
            "fear": "怕打卡断了就真的撑不住。",
            "decision_logic": "要的是可视化的坚持记录和无缝的复盘节奏。",
            "price_sensitivity": 5,
            "brand_anchor": "有成就感的打卡体系",
            "channel_preference": "数据与进度可视化",
            "quote": "我不用安慰，给我进度条就行——我要看着自己好起来。",
        },
    },
    {
        "key": "high_executor_block",
        "seed_name": "拾一",
        "segment": "高执行打卡型",
        "role": "本人",
        "subject": "本人",
        "stage": "戒断行动期",
        "detach_stage": "戒断行动期",
        "weeks_since_breakup": 4,
        "relationship_months": 10,
        "contact_urge": 6,
        "relapse_count": 0,
        "safety_flag": False,
        "dominant": ["B3", "A2", "B11"],
        "decision_style": "果断",
        "blockers": ["删了又加回来过几次", "共同朋友的动态防不胜防"],
        "drivers": ["彻底数字隔离", "清单化执行", "进度反馈"],
        "jtbd": {
            "job_id": "J1",
            "job_owner": "本人",
            "entry_situation": "删了又加、反复纠缠",
            "current_step_id": "d",
            "desired_outcome_ids": ["O5", "O2", "O1"],
            "forces": {
                "push": ["A2"],
                "pull": ["B3", "B11"],
                "anxiety": [],
                "habit_or_alternative": ["A2"],
            },
        },
        "mindset": {
            "core_motive": "屏蔽是第一步，执行要清单化：取关、隐藏、卸载，一次做干净。",
            "fear": "怕自己半途又心软加回来。",
            "decision_logic": "把戒断当项目做：有步骤、有检查项、有进度。",
            "price_sensitivity": 5,
            "brand_anchor": "任务清单+进度反馈型工具",
            "channel_preference": "结构化、可勾选的流程",
            "quote": "一次做不利索，就别做了——我说删，就删干净。",
        },
    },
]


def pick_archetypes(
    count: int,
    *,
    job_ids: Optional[List[str]] = None,
    entry_situations: Optional[List[str]] = None,
) -> List[Dict]:
    """选取原型：优先铺满不同 key，再按「原型复用次数 → Job 复用次数」均衡补齐。

    生成层须对复用实例做叙事差异化（同 key 不可复述同一动机句）。
    """
    import copy

    pool = PERSONA_ARCHETYPES[:]
    if job_ids:
        filtered = [a for a in pool if a.get("jtbd", {}).get("job_id") in job_ids]
        if filtered:
            pool = filtered
    if entry_situations:
        filtered = [
            a
            for a in pool
            if a.get("jtbd", {}).get("entry_situation") in entry_situations
            or any(
                e in (a.get("jtbd", {}).get("entry_situation") or "")
                for e in entry_situations
            )
        ]
        if filtered:
            pool = filtered

    if not pool:
        pool = PERSONA_ARCHETYPES[:]

    chosen: List[Dict] = []
    key_usage: Dict[str, int] = {a["key"]: 0 for a in pool}
    job_usage: Dict[str, int] = {}

    while len(chosen) < count:
        def _score(a: Dict) -> tuple:
            jid = (a.get("jtbd") or {}).get("job_id", "Jx")
            return (key_usage[a["key"]], job_usage.get(jid, 0), a["key"])

        arch = min(pool, key=_score)
        chosen.append(copy.deepcopy(arch))
        key_usage[arch["key"]] += 1
        jid = (arch.get("jtbd") or {}).get("job_id", "Jx")
        job_usage[jid] = job_usage.get(jid, 0) + 1
    return chosen[:count]